### ISSUE TITLE
Possibly make the quarantine_table argument optional in constraint_append

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/mack#101]
`constraint_append` currently requires a `quarantine_table`.  We may want to allow users to set `quarantine_table` to `None` and just throw out the rows that don't match the constraints.

There are probably some users that want to write the bad data to a quarantine table and others that just want to throw out the bad data.  Thoughts?

**Comment by danielbeach** [comment]
@MrPowers I can work on this one if you want.

**Comment by robertkossendey** [comment]
@danielbeach thank you very much, assigned you! :)
