### ISSUE TITLE
Is there a way to rename Delta tables

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/mack#115]
If not, perhaps we can add this functionality

**Comment by danielbeach** [comment]
@MrPowers Mind if I take on this issue? Seems like an interesting one to solve.

**Comment by MrPowers** [comment]
@danielbeach - yea, that'd be great, just assigned you to the issue!

**Comment by danielbeach** [comment]
@MrPowers based on my research renaming a table currently is only supported with delta+spark. Seems like our only option would be to use the `write_deltalake` with the `overwrite` option and rename the table at that point. https://delta-io.github.io/delta-rs/python/usage.html#writing-delta-tables , seem like a heavy-handed approach but our only option with the python standalone reader that I can tell.

If you agree let me know and I can implement that.

**Comment by danielbeach** [comment]
Merged PR, closing issue.
