### ISSUE TITLE
Helper method to quantify number of small files in Delta table

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/mack#16]
The Delta table transaction log includes information on file sizes.

We should make it easy for users to understand how many small files are in their Delta table.  They should be able to run this command to see if it's worth it to run the OPTIMIZE command for example.

It might be easier to implement this functionality with [delta-rs](https://github.com/delta-io/delta-rs), not sure.

**Comment by robertkossendey** [comment]
What kind of information would you expect to see? 

Some ideas that come to my mind: 
- Amount of files
- Average / Median Size of Files
- Amount of Files with size below certain threshold

**Comment by souvik-databricks** [comment]
Apart from the delta-rs package. For Databricks based users I actually had written a function to automatically discover the best suited columns for Z-Order based on the cluster logs. 
@MrPowers what do you think should I add that functionality here? 

It will be something that users will be able to leverage when they use `mack` on Databricks

**Comment by MrPowers** [comment]
@robertkossendey - yep, sounds about right.  We'll have to do number of bytes in file because we won't actually be able to know the file sizes till they're written.  Never know how good snappy will compress.  But the metrics you're listing sound really useful.

**Comment by robertkossendey** [comment]
@MrPowers Those should be easy with delta-spark:

- Amount of files
- Average / Median Size of Files

Since delta_table.details() contains numFiles and sizeInBytes.
The threshold would be more tricky...
I haven't used delta-rs yet, so I don't know whether their API provides more information. Will take a look at the documentation.

**Comment by MrPowers** [comment]
@robertkossendey - better to stick with delta-spark.  We probably don't want to add a new dependency to this project.  Once delta-rs becomes more mature, we'll probably have to create a whole new implementation of this lib.  Let's stick to delta-spark for this lib.

**Comment by robertkossendey** [comment]
Sounds reasonable. I will assign this issue to me then. 
Before we implement additional methods I would like to merge the pre-commit hooks first though, so I can refactor our existing code to make it comply with black / flake8.

**Comment by robertkossendey** [comment]
@MrPowers @souvik-databricks any ideas for the name of the method?

**Comment by souvik-databricks** [comment]
get_delta_fs() maybe?? @robertkossendey

**Comment by MrPowers** [comment]
@robertkossendey - Is there a way to build a DataFrame based on the transaction log with the metadata for all the files in the Delta table?  I'm thinking these columns:

* file_name
* file_size
* min / max values for all the columns

Perhaps we should start by building a function that will create this DataFrame.  That would enable us to easily compute the file sizes & a host of other handy computations (e.g. what percentage of the files can I skip in my Delta table if I apply XYZ predicate on `column1`).  Thoughts?

**Comment by robertkossendey** [comment]
Great idea, will look into it! :)

**Comment by souvik-databricks** [comment]
`+1 ` to this idea

I will also see if I can help you in this.. This will be a killer feature if we can expose a easy dataframe access to the `_delta_log` metadata

**Comment by robertkossendey** [comment]
The problem that I see with accessing the _delta_log directly is that we have to handle all the possible underlying file systems..

`deltaTable.history() / deltaTable.details()` aren't helpful here unfortunately.

**Comment by MrPowers** [comment]
@robertkossendey - going to bring this up with the core team.  Let's go for something like `delta_file_sizes()` in the meantime with whatever implementation works given the current API.

**Comment by MrPowers** [comment]
@robertkossendey @souvik-databricks - FYI, added a feature request to delta-rs for this: https://github.com/delta-io/delta-rs/issues/1031

**Comment by MrPowers** [comment]
We added this.  Hopefully they add a better core API so we can provide an even better implementation in the future.  Getting a count of the number of small files would be better for determining when to compact.
