### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by robertkossendey** [MrPowers/mack#20]
The current version of mack that is available through [pip](https://pypi.org/project/mack/#history) is 0.1.0 which has been released on the 27th of November.

Going forward, how should the deployment approach look like?

@MrPowers

**Comment by MrPowers** [comment]
@robertkossendey - I think I'm the only one that can deploy cause I'm the only one with the credentials (unfortunately).  In the long run, if this project gets more popular, let's figure out a better solution.  In the meantime, just ping me whenever you want a release and I will run the command.  I just need to run `poetry build` and `poetry publish`.

**Comment by robertkossendey** [comment]
Sounds good, I will add this to the CONTRIBUTING.md as soon as I have time to work on it :)
