### ISSUE TITLE
Add Flake8 to our Github Actions Pipeline

### ISSUE THREAD

**Issue by robertkossendey** [MrPowers/mack#22]
Flake8 should be run whenever you merge / push to main with the following plugins:

- flake8-bugbear
- Flake8-pyproject
- pep8-naming

**Comment by robertkossendey** [comment]
@souvik-databricks do you want to take over?

**Comment by souvik-databricks** [comment]
I will setup this pipeline @robertkossendey  You can assign this ticket to me.

**Comment by MrPowers** [comment]
This has been added.
