### ISSUE TITLE
Add is_col_unique function

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/mack#30]
The `is_col_unique` function should return true if all values in the column are unique and false otherwise.

The `drop_duplicates_pkey` function requires a unique primary key column.  We should provide users with an easy way to determine if a column contains unique values.

**Comment by robertkossendey** [comment]
Will take care of this one 👍

**Comment by robertkossendey** [comment]
@MrPowers what do you think of extending the scope from one column to n? That way you can test if a combination of columns is unique, which would be important for composite keys etc.

**Comment by MrPowers** [comment]
@robertkossendey - Yea, I like the idea of extending the scope from one column to `n` - good idea!
