### ISSUE TITLE
Extend the DeltaTable API with mack functions

### ISSUE THREAD

**Issue by robertkossendey** [MrPowers/mack#32]
Our current approach to the helper functions is that they are independent from the DeltaTable class.
Another approach would be to extend the DeltaTable class with mack functions, which would remove the necessity from specifying the delta table as parameter + allow for chaining.

Example:

`delta_table.copy_table(target_path=path)`

I would like to hear your opinions on it.

**Comment by MrPowers** [comment]
@robertkossendey - this is a great question.  Extending core PySpark classes is something I did in the quinn library and I actually ended up regretting it.  See [this file for an example](https://github.com/MrPowers/quinn/blob/main/quinn/extensions/dataframe_ext.py).  

This core class extension became a liability once the `transform` method was added to PySpark.

Core class extensions also make code less readable in my opinion.

Suppose you're looking through the codebase and see this code that someone else wrote: `mack.copy_table(delta_table=deltaTable, target_path=path)`.  You can go to the top of the file, see the `import mack` and easily figure out where the code came from.  

When all you see is `delta_table.copy_table(target_path=path)` in the code, it's hard to decipher that the `copy_table` function comes from mack.  I am going to add a PR with the code design philosophy for this project to expand upon this more generically 🤓

**Comment by robertkossendey** [comment]
Fair points, didn't think of that!
A design philosophy doc would be great to have 👍
