### ISSUE TITLE
Add an append_without_duplicates function

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/mack#4]
Append operations will add duplicate values by default.  The [Delta Lake documentation](https://docs.delta.io/latest/delta-update.html#data-deduplication-when-writing-into-delta-tables&language-python) contains examples showing how to append without adding and duplicates.

Here's the code snippet they use:

```python
deltaTable.alias("logs").merge(
    newDedupedLogs.alias("newDedupedLogs"),
    "logs.uniqueId = newDedupedLogs.uniqueId") \
  .whenNotMatchedInsertAll() \
  .execute()
```

It'd be nice to wrap this in a helper method so users can access this functionality with a single line of code.

**Comment by souvik-databricks** [comment]
Hi @MrPowers I can take this issue. Please assign it to me. Thanks.

**Comment by MrPowers** [comment]
@souvik-databricks - awesome, assigned it to you!

**Comment by souvik-databricks** [comment]
@MrPowers I think we can close the issue now that the PR is merged.
