### ISSUE TITLE
Flake8 does not fail

### ISSUE THREAD

**Issue by robertkossendey** [MrPowers/mack#50]
[This commit](https://github.com/MrPowers/mack/actions/runs/3801340822/jobs/6465708152) broke some Flake rules, but the Action did not fail, but IMO it should fail. WDYT?

@MrPowers @souvik-databricks

**Comment by souvik-databricks** [comment]
@robertkossendey  I can make it fail do you want it to fail? I thought we only want the flake8 checks to be recorded in verbose without the flake pipeline actually failing

**Comment by robertkossendey** [comment]
@souvik-databricks I think you are referring to our black config, there it should not format but only fail. Would be great if you could make flake8 fail :) also we should align the max-code-length in our pyproject with the one in the GitHub Workflow.

**Comment by robertkossendey** [comment]
@souvik-databricks I see that black also does not fail. We should definitely make it fail, but not reformat :)
