### ISSUE TITLE
Small function name error in README docs

### ISSUE THREAD

**Issue by Triamus** [MrPowers/mack#66]
It seems to me the referenced function name in the README docs at https://github.com/MrPowers/mack#drop-duplicates should be `mack.drop_duplicates(delta_table=deltaTable, duplication_columns=["col1"])` but it actually is `mack.drop_duplicates_pkey(delta_table=deltaTable, duplication_columns=["col1"])`.

**Comment by MrPowers** [comment]
@Triamus - thanks for reporting this.  Would you be willing to submit a pull request to fix this?  We'd love to have you as a contributor!

**Comment by Triamus** [comment]
@MrPowers Ya, I was actually thinking about it but I wasn't sure if I have to run the whole test suite locally which would be difficult on the system I'm currently on. Can I do the PR without that? Thanks.

**Comment by MrPowers** [comment]
@Triamus - yea, you don't need to worry about running the test suite.  Just a PR is fine.  Let me know if you need any help!

**Comment by Triamus** [comment]
Thanks, I'll try a PR then.
