### ISSUE TITLE
Add a "constraint append" that appends the valid rows and puts the invalid rows in another table

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/mack#68]
Constraints currently fail the whole transaction when a single row doesn't pass.  It'd be nice to have a function that appends the valid rows and puts the invalid rows in another table.

Motivation:

<img width="534" alt="Screen Shot 2023-01-21 at 3 14 09 PM" src="https://user-images.githubusercontent.com/2722395/213881165-0cad3dd4-338e-45c3-bf25-9dc8a5834928.png">

**Comment by robertkossendey** [comment]
This is also part of #53

**Comment by prasenjitcloudgurua** [comment]
@MrPowers - please assign it to my name.

**Comment by MrPowers** [comment]
@prasenjitcloudgurua - awesome, let me know when the PR is ready for review, so excited!

**Comment by MrPowers** [comment]
@prasenjitcloudgurua - do you still plan to work on this one?  If not, no problem, but let me know so I can assign it to someone else.

**Comment by cs23andris** [comment]
Hi @MrPowers - if @prasenjitcloudgurua is not working on this one, can you please assign it to me?

**Comment by MrPowers** [comment]
Sure thing @cs23andris, assigned it to you
