### ISSUE TITLE
Add better contributing instructions

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/mack#71]
Tell users how to get started with mack on their local machine.

* install poetry
* install the dependencies with poetry
* run the test suite
* anything else?

This is [the file that needs to be updated](https://github.com/MrPowers/mack/blob/main/CONTRIBUTING.md).

**Comment by MrPowers** [comment]
@Triamus - a ready-to-use Docker image is a great idea.  Can you please create a separate issue so we can track that request and get it done?  Thanks!

**Comment by Triamus** [comment]
@MrPowers done in #72 .
