### ISSUE TITLE
Remove code not being used in drop_duplicates_pkey

### ISSUE THREAD

**Issue by brayanjuls** [MrPowers/mack#78]
I was trying to port that function into [Jodie](https://github.com/MrPowers/jodie) project and found that the code below will never get executed because of the validation applied to duplication_columns input parameter. I think it will be good to remove that part just to make the code clear and avoid confusion. 

```python
    else:
        duplicate_records = (
            data_frame.withColumn(
                "row_number",
                row_number().over(
                    Window().partitionBy(primary_key).orderBy(primary_key)
                ),
            )
            .filter(col("row_number") > 1)
            .drop("row_number")
            .distinct()
        )
```

**Comment by MrPowers** [comment]
@brayanjuls - thanks for flagging this.

@robertkossendey - can you please take a look?

**Comment by MrPowers** [comment]
This is fixed now @brayanjuls, thanks for flagging!
