### ISSUE TITLE
Is drop_duplicates the right abstraction?

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/mack#8]
Suppose we have this table:

```
+----+----+----+----+
|col1|col2|col3|col4|
+----+----+----+----+
|   1|   A|   A|   C| # duplicate1
|   2|   A|   B|   C|
|   3|   A|   A|   D| # duplicate1
|   4|   A|   A|   E| # duplicate1
|   5|   B|   B|   C| # duplicate2
|   6|   D|   D|   C|
|   9|   B|   B|   E| # duplicate2
+----+----+----+----+
```

We currently deduplicate it as follows:

```python
mack.drop_duplicates(delta_table=deltaTable, primary_key="col1", duplication_columns=["col2", "col3"])
```

I'm not sure we should have `primary_key` in this function.  Shouldn't this just be this?

```python
mack.drop_duplicates(delta_table=deltaTable, duplication_columns=["col2", "col3"])
```

Let me know if I'm looking at this incorrectly.

**Comment by robertkossendey** [comment]
I agree, and this should also apply to `kill_duplicates` as well. Would be happy to work on that 👍

**Comment by MrPowers** [comment]
@scottsand-db @nkarpov - thoughts?

**Comment by MrPowers** [comment]
Fixed

**Comment by alexeyegorov** [comment]
Primary key is still required for drop_duplicates?! If I see the code correctly, the primary key is used for ordering the values. 

```
  duplicate_records = (
      data_frame.withColumn(
          "row_number",
          row_number().over(
              Window().partitionBy(duplication_columns).orderBy(primary_key)
          ),
      )
      .filter(col("row_number") > 1)
      .drop("row_number")
      .distinct()
  )
```

Basically, the list of duplication columns identify an entry as unique. `pkey` then identifies which value will be kept. In my understanding this is not the definition of the primary key.

If my assumption is correct, it would match better to call the parameter `order_by_key` or something similar plus if it is descending or ascending. In my case I would probably consider the timestamp from the original load date which is definitely not the primary key. ;) 

@MrPowers @robertkossendey
