### ISSUE TITLE
Function to get the latest version of a Delta table

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/mack#88]
Delta tables can have multiple versions.  v0, v1, v2, etc.

The Jodie library has a `latest_version` function that returns the latest version of the Delta table: https://github.com/MrPowers/jodie#latest-version-of-delta-table

We should add a `mack.latest_version` function to access the same functionality in PySpark.

**Comment by danielbeach** [comment]
@MrPowers you mind if I take this one?

**Comment by MrPowers** [comment]
@danielbeach - sure thing, just assigned it to you.

**Comment by danielbeach** [comment]
@MrPowers I pushed up a PR, happy to make changes to make the code "fit" in this repo more, still trying to learn the style you all have going on here. Thanks.
