### ISSUE TITLE
Switch out Flake8 with Ruff

### ISSUE THREAD

**Issue by robertkossendey** [MrPowers/mack#93]
We should switch from flake8 to Ruff

Motivation:

Ruff is significantly faster (it should save us free minutes of GH Actions)
Ruff will replace all isort, flake and pylint by one dependency
Ruff is configured in one place (pyproject.toml): [tool.ruff] instead of different files/sections

**Comment by MrPowers** [comment]
@robertkossendey - yes, let's do it.  Let me know if you'd like to work on this and I'll assign it to you.

If anyone else would like to grab it, just comment "take" and I will assign it to you.

**Comment by danielbeach** [comment]
@MrPowers I actually just implemented ruff at work in our Git and CircleCI workflow a few days ago. I would he happy to attempt this one if you want.
